### ISSUE TITLE
Monitoring a Kubernetes cluster with Prometheus and Grafana

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#12]
Finally I'm back working on JupyterHub/Kubernetes/Jetstream!

As part of @julienchastang's project, I wanted to look into tools to help maintain a long-running production Kubernetes / JupyterHub deployment.
First thing is a GUI to easily monitor the cluster, I completed my testing and here the blog post:

https://zonca.github.io/2019/04/kubernetes-monitoring-prometheus-grafana.html

@ktyle, @rsignell-usgs, please take a look and send me feedback.

**Comment by julienchastang** [comment]
Great! I will give it a shot some time this week.

**Comment by ktyle** [comment]
Same here, although may need to wait a couple more weeks until semester wraps up here @ UAlbany ...

**Comment by julienchastang** [comment]
I gave this a shot. The thing is my set up is a bit complex. I run openstack (therefore the kube client) from a docker container, itself running on a cloud VM (I run Jetstream from Jetstream). Doing a `curl localhost:3000` from within the container does indeed yield something that looks about right. However, even with the correct docker port mapping and the necessary security groups open, any attempts to access outside the container  fail:

```
curl localhost:3000
curl: (56) Recv failure: Connection reset by peer
```

Same would be true outside the VM.  I'm not sure if the technology here is preventing me from accessing Prometheus/Grafana in this manner maybe due to security concerns. I run these sorts of setups all the time, though, for other things like tomcat.

**Comment by zonca** [comment]
what I do is I install kubectl also on my laptop, then copy the `.kube/config` to the laptop with `scp -r KUBECTLMACHINE:~/.kube/config ~/.kube` 
 and run `ssh ubuntu@$IP -f -L 6443:localhost:6443 sleep 3h` from the laptop and then run the `port-forward` command locally on the laptop.

**Comment by julienchastang** [comment]
Yes that worked! Stupid question, but how do you login? Where can you set the auth creds / tokens or allow anonymous? Thanks!

**Comment by zonca** [comment]
I don't remember, Have you tried admin and as user and also password?

**Comment by zonca** [comment]
yes, it mentioned here: https://github.com/coreos/kube-prometheus#access-the-dashboards

it is `admin` `admin`.

you can costumize everything, but that gets pretty complicated because you have to rebuild the whole project with a pretty strange build system based on `jsonnet`.

**Comment by zonca** [comment]
added credentials and port forward from laptop to blog post
