### ISSUE TITLE
terraform version

### ISSUE THREAD

**Issue by davidedelvento** [zonca/jupyterhub-deploy-kubernetes-jetstream#17]
At https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html it is said to install terraform without specifying verion. The latest at time of writing, namely v0.12 reports a lot of errors. It looks like they have changed a lot.
I suggest to specify to use v0.11.x (I tried x=14 and it worked).

**Comment by zonca** [comment]
just checking, you are using the last version of the tutorial from https://zonca.github.io/2019/02/kubernetes-jupyterhub-jetstream-kubespray.html, right?

**Comment by davidedelvento** [comment]
Well, now @vanderwb and I are (but before we did not). However this issue refers to something that happened before getting to the point where they diverge....

**Comment by zonca** [comment]
fixed by https://github.com/zonca/zonca.github.io-source/commit/78be855dd569a3d281865c407d361d3dfc5d696e

**Comment by pibion** [comment]
I've tried running `bash terraform_init.sh` following the instructions at https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html and switching to the 2.8.2 branch as described in https://zonca.github.io/2019/02/kubernetes-jupyterhub-jetstream-kubespray.html.

I have version 11.14 of terraform installed, but it doesn't seem to recognize the options in terraform_init.sh, 

```
terraform init -var-file=cluster.tf -var "cluster_name=${CLUSTER/_/-}" ../../contrib/terraform/openstack
```

**Comment by zonca** [comment]
can you post the error message?

**Comment by pibion** [comment]
So ... now `bash terraform_init.sh` seems to be working.  

The only change is that I closed my terminal and then re-opened it - is it possible that could have an effect?

~~However, I'm now getting an error when I try `bash terraform_apply.sh`  The error message isn't very helpful, it just says~~

```
Error:

```

It seems the issue was not sourcing my openrc in my new shell.

For reference, I'm using terraform 0.11.14.

**Comment by glass-ships** [comment]
Similar issue: 
Terraform version 0.11.11

At first, running `bash terraform_init.sh` just returned the help menu for `terraform init`,
but after closing and opening a fresh shell session, and doing `source .openrc`, I can:

- Successfully run `bash terraform_init.sh` 

- Fail to run `bash terraform_apply.sh`  
    Returns the following: 

```bash
Error: module.compute.openstack_compute_keypair_v2.k8s: 1 error(s) occurred:

* module.compute.openstack_compute_keypair_v2.k8s: file: open /home/josh/snap/terraform/216/.ssh/id_rsa.pub: no such file or directory in:

${chomp(file(var.public_key_path))}
```

EDIT: Just out of curiosity, what kind of changes in 0.12.x break compatibility with the `jetstream_kubespray`?

**Comment by zonca** [comment]
have you tried to use the Magnum based deployment tutorial instead?
https://zonca.github.io/2019/06/kubernetes-jupyterhub-jetstream-magnum.html
it should be a lot simpler

**Comment by glass-ships** [comment]
Thanks zonca, it turns out i had installed `terraform` via SNAP, which works, but results in a faulty search for `..../.ssh`. After downloading and copying the binary directly from Terraform, all the `terraform_XXX.sh` scripts work as expected. 

I'll continue working through your jupyterhub/kubespray/terraform guide and see how far i get!
