### ISSUE TITLE
Manually Scaling Not Working

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#54]
[Manual scaling](https://zonca.dev/2019/02/scale-kubernetes-jupyterhub-manually.html) not working probably as a result of moving to JS2.  Calling `terraform_apply.sh` again destroys the master node (this did not happen on JS1).

`k8s_scale` eventually yields:

```
fatal: [sau-f2022-1]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/kubeadm init phase --config /etc/kubernetes/kubeadm-config.yaml upload-certs --upload-certs", "msg": "[Errno 2] No such file or directory: b'/usr/local/bin/kubeadm'", "rc": 2}
```

**Comment by julienchastang** [comment]
Eventually you have to call `k8s_install.sh` and re-install everything. Also the PVCs are lost so user data is gone. Ping @robertej09.

**Comment by julienchastang** [comment]
Interestingly, if you go through those steps a **second time**, it appears to work and no data has been lost.

**Comment by zonca** [comment]
ok, I can test on my deployment in the next few days

**Comment by zonca** [comment]
I tested on a freshly created deployment,
when I change the number of nodes and call `terraform_apply.sh`, the master node and the pre-existing node **are not** deleted.
Are you sure there has not been any other change in `cluster.tfvars`?

**Comment by zonca** [comment]
I'm now testing `k8s_scale.sh`

**Comment by zonca** [comment]
yes, in my simple test everything worked:

```
k get nodes
NAME                 STATUS   ROLES                  AGE     VERSION
kubejs2-1            Ready    control-plane,master   5h7m    v1.22.5
kubejs2-k8s-node-1   Ready    <none>                 5h5m    v1.22.5
kubejs2-k8s-node-2   Ready    <none>                 8m17s   v1.22.5
kubejs2-k8s-node-3   Ready    <none>                 8m17s   v1.22.5
```

**Comment by julienchastang** [comment]
I wonder if this has anything to do with this line:

```
k8s_master_fips = ["149.165.XXX.XXX"]
```

which we uncomment with the desired IP, but you may have commented out. In fact, I wonder if we should comment it out when scaling. This is just a hunch or a guess. I have not tested this hypothesis.

**Comment by zonca** [comment]
it was easy to test, so I tried, no it works fine also with a pre-reserved floating IP.

    Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

the only strange behavior is that the first time I ran terraform to create the resources (not to scale), I got:

```
Error: Error creating OpenStack server: Bad request with: [POST https://js2.jetstream-cloud.org:8774/v2.1/servers], error message: {"bad
Request": {"code": 400, "message": "Network 930fae38-d73b-4768-9b7b-0365371bb408 requires a subnet in order to boot instances on."}}
```

But I think it was just a delay in creating the subnet, I just reran it again and it worked.

**Comment by ana-v-espinoza** [comment]
@zonca, @julienchastang,

I thought this through over the weekend and I believe I've discovered the issue, and the discrepancy between our two cases. Julien and myself both tried up-scaling previously existing clusters, rather than a cluster created specifically for troubleshooting this issue.

I have just ran a

`terraform plan -var-file=cluster.tfvars -var="cluster_name=$CLUSTER" -var="network_name=${CLUSTER}-network" ../../contrib/terraform/openstack`

in two other pre-existing clusters (without changing _anything_ in `cluster.tfvars`) to see what changes terraform would want to make if we ran a `terraform apply`. For both clusters, terraform wanted to recreate the master node. The output of `terraform plan` reveals why. Shown below is only the relevant output:

```
  # module.compute.openstack_compute_instance_v2.k8s_node_no_floating_ip[3] must be replaced
-/+ resource "openstack_compute_instance_v2" "k8s_node_no_floating_ip" {
      ~ image_id            = "68445a85-f0de-452d-b91b-6acb91dedf05" -> "fb37f2eb-101c-46ee-8a7e-ac3e9b910671" # forces replacement                                                                                                       
}
```

Our `cluster.tfvars` has `image = "Featured-Ubuntu20"`, whose ID appears to have changed since the cluster was first created.

This would explain why a newly created cluster for the purposes of testing the upscaling procedure would proceed without error, and also why Julien did not see the error after attempting to upscale a second time (as per his message above), as the first `terraform apply` already brought the node's image up to date.

Any advice on how to force terraform to keep the existing image on the master node? Thanks!

**Comment by zonca** [comment]
good catch! that was hard to find.
I would try to use `--limit`:

https://kubespray.io/#/docs/nodes?id=_2-run-scaleyml

**Comment by ana-v-espinoza** [comment]
Thanks for the swift response! Unless I'm misunderstanding something, the `--limit` option is meant to be used on the kubespray/ansible level as opposed to the terraform/openstack/VM level.

After doing some digging I found the terraform docs on [lifecycles](https://www.terraform.io/language/meta-arguments/lifecycle), which may be what we're looking for. Adding following block to this [resource](https://github.com/zonca/jetstream_kubespray/blob/5d2505db9145e01706faa1a9ec5afb13797f166c/contrib/terraform/openstack/modules/compute/main.tf#L211) (as well as other master node resources, if necessary) in the terraform compute config could do the trick:

```
lifecycle {
  ignore_changes = [ image_id ]
}
```

I will be testing this shortly, however I'm hesitant to suggest that this change should be committed to the repository, as I'm sure there may be situations where we'd want to use terraform to upgrade our instances' image.

**Comment by zonca** [comment]
if it works I would like to add to the tutorial with explanation on how to remove it if need be

**Comment by ana-v-espinoza** [comment]
This appears to work as I expect it to. Which do you think is the better option?

1. Update all relevant resources in the main.tf I referenced above to include the lifecycle block and add a note about it in your tutorial in case users want to remove these lines
2. Don't update main.tf, but instead update your tutorial to advise users to exercise caution when upscaling (or otherwise re-running `terraform apply`)
   - Ask them to "look before you leap," ie, run a `terraform plan` before applying any actual changes
   -  Tell them how to solve the issue of terraform unexpectedly destroying infrastructure

I think the first solution requires less user effort, but the second one is probably better terraform practice ("look before you leap") and offers a way forward in the case where terraform wants to re-create a resource for reasons other than image IDs changing.

Let me know how I can help!

**Comment by zonca** [comment]
I'd rather do `1.`, this is a known problem we have a solution for, let's provide it for the user.

If you provide a pull request with the fixes in `main.tf`, I can then add the text in the tutorial.

**Comment by julienchastang** [comment]
Closed by https://github.com/zonca/jetstream_kubespray/pull/18

**Comment by julienchastang** [comment]
Just an update here that https://github.com/zonca/jetstream_kubespray/pull/18 works as advertised. I just scaled/added nodes in a "real world" situation. The only thing is I did need to call the `k8s_scale.sh` for the scaling to fully take affect. Otherwise, the JupyterHub would display `503` errors. For some reason, I thought the Hub remained accessible after the call to the terraform script, but before calling `k8s_scale.sh`, but I may be remembering wrong.

**Comment by zonca** [comment]
thanks @julienchastang, that seems really strange, Terraform should only have created the new nodes, but Kubernetes has no access to those nodes until you call `k8s_scale.sh` to add them to the cluster.
Is it possible that Terraform patched some other Openstack resource, maybe networking? It would be useful to check in the logs.

**Comment by julienchastang** [comment]
OK, I'll try to provide Terraform log information. Is there a specific place I should be looking? There is Terraform output generated when running the Terraform script from the command line. Is that what you are looking for?

**Comment by zonca** [comment]
I think the output should be enough, I would like to make sure that no networking object was modified by Terraform

**Comment by julienchastang** [comment]
Hi. I am having trouble reproducing this right now because I need an environment where the current Ubuntu VM ID offered by JS2 needs to be different from the VM running on the cluster. I will update this issue when I have the chance.

**Comment by zonca** [comment]
closing this for now.
